name: ci

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  DOTNET_ROLL_FORWARD: Major

on:
  push:
    branches:
    - main
    - feature/*
    - release/*
    paths:
      - ".github/workflows/**"
      - "scripts/**"
      - "src/**"
      - "GitVersion.yml"
  pull_request:
    types:
    - closed
    branches:
    - main
    paths:
      - ".github/workflows/**"
      - "scripts/**"
      - "src/**"
      - "GitVersion.yml"
  workflow_dispatch:
    inputs: {}

# https://github.com/PowerShell/PowerShellGet/issues/163
jobs:
  powershell:
    uses: cloud-tek/automation/.github/workflows/publish.yml@main
    name: powershell
    with:
      NuGetApiUrl:  'https://api.nuget.org/v3/index.json'
      modules: |
        [
          {
            "id": "CloudTek.Automation.Shell"
          },
          {
            "id": "CloudTek.Automation.K8S"
          }
        ]
    secrets:
      NuGetApiKey:  '${{ secrets.NUGET_API_KEY }}'
