name: ci

env:
  NETCORE_VERSION: 6.0.100
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  DOTNET_ROLL_FORWARD: Major

on:
  push:
    branches:
    - main
    - feature/*
    - release/*
    paths:
      - ".github/workflows/**"
      - "build/**"
      - "CloudTek.Automation.*/**"
      - "GitVersion.yml"
  pull_request:
    types:
    - closed
    branches:
    - main
    paths:
      - ".github/workflows/**"
      - "build/**"
      - "CloudTek.Automation.*/**"
      - "GitVersion.yml"
  workflow_dispatch:
    inputs: {}

jobs:
  publish:
    uses: cloud-tek/automation/.github/workflows/publish.yml@main
    name: publish
    with:
      Module: CloudTek.Automation.K8S
      NuGetApiUrl:  'https://nuget.pkg.github.com/cloud-tek/index.json'
    secrets:
      NuGetFeedCloudTek:  ${{ secrets.NUGET_FEED_CLOUDTEK }}
      NuGetUsername:      ${{ secrets.NUGET_USERNAME }}
      NuGetPassword:      ${{ secrets.NUGET_PASSWORD }}
