name: ci
# test:
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  DOTNET_ROLL_FORWARD: Major
  Modules: |
    [
      {
        "id": "CloudTek.Automation.Shell"
      },
      {
        "id": "CloudTek.Automation.K8S"
      }
    ]

on:
  push:
    branches:
    - main
    - feature/*
    - release/*
    paths:
      - ".github/workflows/**"
      - "scripts/**"
      - "src/**"
      - "tests/**"
      - "GitVersion.yml"
  pull_request:
    types:
    - closed
    branches:
    - main
    paths:
      - ".github/workflows/**"
      - "scripts/**"
      - "src/**"
      - "GitVersion.yml"
  workflow_dispatch:
    inputs: {}

# https://github.com/PowerShell/PowerShellGet/issues/163
jobs:
  publishing-tests:
    uses: ./.github/workflows/publishing-tests.yml
    name: publishing-tests
  module-tests:
    uses: ./.github/workflows/module-tests.yml
    name: module-tests
    secrets:
      pat: ${{ secrets.REPOSITORY_PAT }}
    with:
      modules: |
        [
          {
            "id": "CloudTek.Automation.Utilities"
          },
          {
            "id": "CloudTek.Automation.Git"
          },
          {
            "id": "CloudTek.Automation.Shell"
          },
          {
            "id": "CloudTek.Automation.K8S"
          }
        ]
  prepublish:
    needs:
    - publishing-tests
    - module-tests
    uses: ./.github/workflows/prepublish.yml
    if: github.ref == 'refs/heads/main'
    name: prepublish
    with:
      modules: |
        [
          {
            "id": "CloudTek.Automation.Shell"
          },
          {
            "id": "CloudTek.Automation.K8S"
          }
        ]
  publish:
    needs:
    - prepublish
    uses: ./.github/workflows/publish.yml
    if: github.ref == 'refs/heads/main'
    name: publish
    with:
      NuGetApiUrl:  'https://api.nuget.org/v3/index.json'
      modules: |
        [
          {
            "id": "CloudTek.Automation.Shell"
          },
          {
            "id": "CloudTek.Automation.K8S"
          }
        ]
    secrets:
      NuGetApiKey:  '${{ secrets.NUGET_API_KEY }}'
