name: "nuke"

on:
  workflow_call:
    secrets:
      NuGetFeedCloudTek:
        description: "NuGet Feed (cloud-tek)"
        required: false
      NuGetUsername:
        description: "NuGet Username"
        required: false
      NuGetPassword:
        description: "NuGet Password"
        required: false
    inputs:
      NuGetApiUrl:
        description: "Target NuGet Feed Url"
        type: string
        required: false
      Module:
        description: "Powershell module to publish"
        type: string
        required: true

jobs:
  powershell:
    name: nuke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - id: auto-release
        uses: cloud-tek/actions/auto-release@0.19
        with:
          branch: main
          configuration: .config/configuration.changelog.json
      - name: setup gitversion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: run giversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: nuget.config (pwsh)
        shell: pwsh
        run: |
          $nuget = @"
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
              <add key="nuget.cloudtek.io" value="${{ secrets.NuGetFeedCloudTek }}" protocolVersion="3"/>
            </packageSources>
            <packageRestore>
              <add key="enabled" value="True" />
              <add key="automatic" value="True" />
            </packageRestore>
            <bindingRedirects>
              <add key="skip" value="False" />
            </bindingRedirects>
            <packageManagement>
              <add key="format" value="0" />
              <add key="disabled" value="False" />
            </packageManagement>
            <packageSourceCredentials>
              <nuget.cloudtek.io>
                <add key="Username" value="${{ secrets.NuGetUsername }}"/>
                <add key="ClearTextPassword" value="${{ secrets.NuGetPassword }}" />
              </nuget.cloudtek.io>
            </packageSourceCredentials>
          </configuration>
          "@
          $nuget | Out-File -FilePath ${{ github.workspace }}/nuget.config
      - name: diag
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          tree .
          cat ./global.json
      - name: publish-module.ps1
        shell: pwsh
        working-directory: ${{ github.workspace }}/src/${{ inputs.Module }}
        run: |
          ${{ github.workspace }}/scripts/Publish-Module.ps1 `
            -module ${{ inputs.Module }} `
            -username ${{ secrets.NuGetUsername }} `
            -password ${{ secrets.NuGetPassword }} `
            -organization "cloud-tek";
