name: "publish-local"

on:
  workflow_call:
    inputs:
      modules:
        description: "Powershell modules to publish (json, array of objects)"
        type: string
        required: true

jobs:
  local:
    # strategy:
    #   max-parallel: 1
    #   matrix:
    #     module: ${{ fromJson(inputs.modules) }}
    name: ${{ matrix.module.id }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - id: auto-release
        uses: cloud-tek/actions/auto-release@0.19
        with:
          branch: main
          configuration: .config/configuration.changelog.json
      - name: setup gitversion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: run giversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: nuget.config (pwsh)
        shell: pwsh
        run: |
          $nuget = @"
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
            </packageSources>
            <packageRestore>
              <add key="enabled" value="True" />
              <add key="automatic" value="True" />
            </packageRestore>
            <bindingRedirects>
              <add key="skip" value="False" />
            </bindingRedirects>
            <packageManagement>
              <add key="format" value="0" />
              <add key="disabled" value="False" />
            </packageManagement>
          </configuration>
          "@
          $nuget | Out-File -FilePath ${{ github.workspace }}/nuget.config
      - name: Install-Module PowershellGet
        shell: pwsh
        working-directory: ${{ github.workspace }}
        run: |
          Install-Module PowershellGet -Force -AllowPrerelease;
      - name: Version.ps1
        shell: pwsh
        working-directory: ${{ github.workspace }}/scripts
        run: |
          ./Version.ps1 `
            -modules ${{ inputs.modules }} `
            -version ${{ env.GitVersion_NuGetVersionV2 }};
      - name: Publish-Local.ps1
        shell: pwsh
        working-directory: ${{ github.workspace }}/scripts
        run: |
          ./Publish-Local.ps1 `
            -modules ${{ inputs.modules }};
      - name: ls packages
        shell: bash
        working-directory: ${{ github.workspace }}/packages
        run: |
         ls -l
